fix(deps): pin unicode-segmentation <1.12 in WASM guest crates
unicode-segmentation 1.12.0 made UnicodeWords struct private, breaking
heck 0.4.1 which is used transitively by wit-bindgen 0.21. This caused
all CI builds to fail with:

  error[E0603]: struct `UnicodeWords` is private

Pin unicode-segmentation to <1.12 in the affected WASM guest crates
until wit-bindgen upgrades to heck 0.5+.

Signed-off-by: Simon Lin <simonslin@gmail.com>
Signed-off-by: Simo Lin <linsimo.mark@gmail.com>